= etsy-to-gnucash
Stéphane TRÉBEL <stephane.trebel@gmail.com>
v1.0.0, 2022-11-01
:toc:

== About

This repository provides a tool to convert Etsy Finance CSV export file
to a format that can be imported in GNUCash transaction import tool.
If you need more info on how it works and why it exists, feel free to dive in the link:./detailed-documentation.adoc[Detailed Documentation].

WARNING: etsy-to-gnucash is in its infancy and thus localization is not currently supported (feel free to help me with it through PRs !). CSV are meant to be in Etsy *FRENCH* version, so headers listed here will be in french. The rest of the code (notably the accounts) can be specified with whatever you have setup in GNUCash so localization will not matter here but for CSV parsing and handling, sorry but it's french-based 🙏)

== How to use

* `npm ci`
* `npm run build`
* `node dist/etsy-to-gnucash.js --inputDir=<dir having csv files to convert> --outDir=<dir receiving converted csv files>`
* `outDir` will then have as many files as `inputDir`
* Every file in `outDir` will be suffixed with `_converted` to avoid
overwriting if `inputDir` === `outDir`
* cleanup, either in `inputDir` or `outDir` is left to you

== How to configure GNUCash to import CSV transactions

_TODO_

== Tests

Of course there are tests, just `npm run test` !
